name: Docker push container at org level (GITHUB_TOKEN)
on: workflow_dispatch

permissions:
 packages: write
 
env:
 pkg: "drupal"

jobs:
 all:
  runs-on: self-hosted
  steps:
      - name: Setup node
        uses: actions/package-action@1.0.1
